baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
