[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'page'

[taxonomies]
  tag = 'tags'
  author = 'authors'
  post = 'posts'
  series = 'series'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
