name = 'Epsilon Delta Hugo Theme'
license = 'MIT'
licenselink = 'https://github.com/Epsilondelta-ai/hugo-theme.git/LICENSE'
description = 'Epsilon Delta tech blog theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/Epsilondelta-ai/hugo-theme.git'

# If you have a running demo of the theme
demosite = 'https://tech.epsilondelta.ai'

version = '0.1.0'

tags = ['blog', 'tech', 'tailwindcss', 'responsive']
features = ['responsive', 'seo']

[author]
  name = 'juunini'
  homepage = 'https://github.com/juunini'
